wallpaper {
    monitor = DP-1
    path = /home/ariel/Pictures/wallpapers/wallhaven-9dxv8x_2560x1440.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/ariel/Pictures/wallpapers/wallhaven-76evl9_2560x1440.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/ariel/Pictures/wallpapers/wallhaven-pk92xe_2560x1440.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/ariel/Pictures/wallpapers/wallhaven-lqypvq_3840x2160.png
    fit_mode =
}

splash = false

# ...